version: '2'

services:
  app:
    image: bugfire/home_dashboard:latest
    volumes:
      # - "/share/Docker/Volumes/remo_watch/config:/config:ro"
      - "./config:/config:ro"
    restart: always
    cpu_shares: 20
    mem_limit: "2048m"
    ports:
      - "3000:3000"
    build:
      context: .
