version: '2'

services:
  app:
    image: bugfire/home_dashboard:latest
    volumes:
      - "/share/Docker/Volumes/home_dashboard/config:/config:ro"
    restart: always
    cpu_shares: 20
    mem_limit: "2048m"
    ports:
      - "3000:3000"
